/* ================================================================
   MediQueue - Queue Management Module
   Receptionists organize and update the patient queue that was
   auto-generated by the appointment booking module.
================================================================ */

DB.seed();
requireRole("receptionist");

function renderQueue() {
  const tbody = document.querySelector("#queueTable tbody");
  const queue = DB.load(DB.keys.QUEUE);

  tbody.innerHTML = queue
    .map(
      q => `<tr>
        <td>${q.token}</td>
        <td>${q.patientName}</td>
        <td><span class="badge ${q.status.replace(" ", "-")}">${q.status}</span></td>
        <td>${renderActionButtons(q)}</td>
      </tr>`
    )
    .join("");
}

function renderActionButtons(q) {
  if (q.status === "waiting") {
    return `<button style="width:auto;" onclick="updateStatus(${q.id}, 'in progress')">Call In</button>`;
  }
  if (q.status === "in progress") {
    return `<button style="width:auto;" onclick="updateStatus(${q.id}, 'done')">Mark Done</button>`;
  }
  return "-";
}

function updateStatus(queueId, newStatus) {
  let queue = DB.load(DB.keys.QUEUE);
  queue = queue.map(q => (q.id === queueId ? { ...q, status: newStatus } : q));
  DB.save(DB.keys.QUEUE, queue);
  renderQueue();
}

renderQueue();
